package uk.ac.ed.inf.dataTypes;

public enum OrderValidationCode{

    UNDEFINED,
    NO_ERROR,
    CARD_NUMBER_INVALID,
    EXPIRY_DATE_INVALID,
    CVV_INVALID,

    TOTAL_INCORRECT,
    PRICE_FOR_PIZZA_INVALID,
    PIZZA_NOT_DEFINED,
    MAX_PIZZA_COUNT_EXCEEDED,
    PIZZA_FROM_MULTIPLE_RESTAURANTS,
    RESTAURANT_CLOSED,

    EMPTY_ORDER
}
